---
title: "cleaning_merging_FRONTEX_data"
output: pdf_document
date: "2024-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clean up workspace
rm(list=ls())

# Set working directory
# Note: Please adjust the file paths below to match the location where you saved my folder in your directory structure.
setwd("~/Desktop/GHVT6_MScThesis")
```

```{r}
# Load packages
list.of.packages <- c("readxl", "readr", "openxlsx", "writexl", "dplyr", "tidyr", "ggplot2", "lubridate", "janitor", "purrr", "stringr")
invisible(lapply(list.of.packages, library,
                 character.only = TRUE))
```

```{r}
#############################################################
##### Detections of illegal border-crossings statistics #####
#############################################################

#### Routes of interest ####
# Circular route from Albania to Greece
# Eastern Mediterranean

# Load data
frontex <- read_excel("GHVT6_Raw_data/Monthly_detections_of_IBC.xlsx")

# Filter for specific routes
frontex <- frontex %>%
  filter(Route %in% c("Circular Route from Albania to Greece", "Eastern Mediterranean Route"))

# Gather the date columns to make the data long format for easier manipulation
frontex <- frontex %>%
  gather(key = "month_year", value = "count", -Route, -"Border type or inland", -Nationality)

# Convert month_year to actual date format
frontex <- frontex %>%
  mutate(date = as.Date(paste0("01", substr(month_year, 4, 7), "-", substr(month_year, 1, 3)), format = "%d%Y-%b"))

# Drop the original month_year column if no longer needed
frontex <- frontex %>%
  select(-month_year)

# Clean up country names by removing special characters
frontex <- frontex %>%
  mutate(Nationality = gsub("[^A-Za-z\\s]", "", Nationality)) # Removes anything not a letter or space

# Rename the columns and remove unnecessary ones
frontex <- frontex %>%
  rename(
    illegal_border_crossings = count,
    country = Nationality,
    year_month = date
  ) %>%
  select(-Route, -`Border type or inland`, illegal_border_crossings, country, year_month)

# View the modified data
head(frontex)

# Save the cleaned data
write_xlsx(frontex, "GHVT6_Final_data/cleaned_frontex_data.xlsx")
```

